import { createAsyncThunk, createSlice } from "@reduxjs/toolkit";
import {
    REGISTER,
    LOGIN,
    FORGOT,
    CHANGE_PASSWORD,
    IS_EMAIL_IN_RECORD
} from "./actions";
import {
    changePasswordRequest,
    forgotPasswordRequest,
    loginRequest,
    registerRequest,
    isEmailAlreadyInRecord
} from "../../services";

const initialState = {
    keepLoggedIn: false,
    isLoggedIn: false,
    isInitialized: true,
    user: null,
    status: "idle",
    reqResponse: null,
    alert: "none",
    isEmailExistStatus: "idle",
    isEmailExistResponse: null,
    changePasswordStatus: "idle",
    changePasswordRes: null,
};

// Make async login request.
export const isEmailInRecordAsync = createAsyncThunk(
    IS_EMAIL_IN_RECORD,
    async ( { reqObj } ) => {
        const response = await isEmailAlreadyInRecord( reqObj );
        // The value we return becomes the `fulfilled` action payload
        return response.data;
    }
);

export const loginAsync = createAsyncThunk(
    LOGIN,
    async ( { userLoginObj } ) => {
        const response = await loginRequest( userLoginObj );
        // The value we return becomes the `fulfilled` action payload
        return response.data;
    }
);

export const registerAsync = createAsyncThunk(
    REGISTER,
    async ( { registerObject } ) => {
        const response = await registerRequest( registerObject );
        // The value we return becomes the `fulfilled` action payload
        return response.data;
    }
);

export const forgotAsync = createAsyncThunk(
    FORGOT,
    async ( { passwordForgotObject } ) => {
        const response = await forgotPasswordRequest( passwordForgotObject );
        // The value we return becomes the `fulfilled` action payload
        return response.data;
    }
);

export const changePasswordAsync = createAsyncThunk(
    CHANGE_PASSWORD,
    async ( { changePasswordObject } ) => {
        const response = await changePasswordRequest( changePasswordObject );
        // The value we return becomes the `fulfilled` action payload
        return response.data;
    }
);

export const authSlice = createSlice( {
    name: "auth",
    initialState,
    // The `reducers` field lets us define reducers and generate associated actions
    reducers: {
        logout: ( state ) => {
            state.user = null;
            state.isLoggedIn = false;
        },
        setLoginTrue: ( state ) => {
            state.isLoggedIn = true;
        },
        setKeepLoggedIn: ( state, action ) => {
            state.keepLoggedIn = action.payload;
        },
        setUser: ( state, action ) => {
            state.user = action.payload;
        },
        setAuthAlert: ( state, action ) => {
            state.alert = action.payload;
        },
        resetChangePasswordRes: ( state ) => {
            state.changePasswordRes = null;
        }
    },
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other reducers.
    extraReducers: ( builder ) => {
        builder
            .addCase( loginAsync.pending, ( state ) => {
                state.status = "loading";
                state.user = null;
            } )
            .addCase( loginAsync.fulfilled, ( state, action ) => {
                state.status = "idle";
                state.user = action.payload;
            } )
            .addCase( registerAsync.pending, ( state ) => {
                state.status = "loading";
                state.user = null;
            } )
            .addCase( registerAsync.fulfilled, ( state, action ) => {
                state.status = "idle";
                state.user = action.payload;
            } )
            .addCase( forgotAsync.pending, ( state ) => {
                state.status = "loading";
                state.user = null;
            } )
            .addCase( forgotAsync.fulfilled, ( state, action ) => {
                state.status = "idle";
                state.user = action.payload;
            } )
            .addCase( changePasswordAsync.pending, ( state ) => {
                state.changePasswordStatus = "loading";
                state.changePasswordRes = null;
            } )
            .addCase( changePasswordAsync.fulfilled, ( state, action ) => {
                state.changePasswordStatus = "idle";
                state.changePasswordRes = action.payload;
            } )
            .addCase( isEmailInRecordAsync.pending, ( state ) => {
                state.isEmailExistStatus = "loading";
                state.isEmailExistResponse = null;
            } )
            .addCase( isEmailInRecordAsync.fulfilled, ( state, action ) => {
                state.isEmailExistStatus = "idle";
                state.isEmailExistResponse = action.payload;
            } );
    }
} );

export const {
    logout,
    setLoginTrue,
    setKeepLoggedIn,
    setUser,
    setAuthAlert,
    resetChangePasswordRes
} = authSlice.actions;

// Select a auth from the state.
export const selectAuth = ( state ) => state.auth;

export default authSlice.reducer;
